# Generated by Django 4.2.7 on 2026-01-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exeat_app", "0002_student_house_housemistress"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="housemistress",
            name="house",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="exeat_app.house"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="exeat_app.house",
            ),
        ),
    ]
