# Generated by Django 4.2.7 on 2026-01-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exeat_app", "0003_house_alter_housemistress_house_alter_student_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_photos/"),
        ),
    ]
