# Generated by Django 4.2.7 on 2026-01-02 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exeat_app", "0004_student_guardian_name_student_guardian_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exeat",
            name="signed_in_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_in_exeats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exeat",
            name="signed_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exeat",
            name="signed_out_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_out_exeats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exeat",
            name="signed_out_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exeat",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("signed_out", "Signed Out"),
                    ("signed_in", "Signed In"),
                    ("overdue", "Overdue"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
